project:
  type: website 
  output-dir: "."
  
website:
  title: ""
  # favicon: img/favicon.ico
  description: 'A collection of data analytics by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true

  navbar:
    background: "#1c4982"
    logo: img/geneseo-logo-squared.png
    pinned: true
    right:
      - icon: code-slash
        text: Class Code
        href: https://github.com/bcdanl/410-code
        target: _blank
      - text: " "
    
  sidebar:
    style: docked
    search: false
    collapse-level: 0
    contents:
      - text: ğŸ  Home
        href: index.qmd
      - text: ğŸ““ Syllabus
        href: syllabus.qmd
      - text: ğŸ…± Brightspace
        href: https://mylearning.suny.edu/d2l/home/2534337
        target: _blank
      
      - text: ğŸš€ Lecture
        href: listing-danl-410-lec.qmd
      - text: âŒ¨ï¸ Classwork
        href: listing-danl-410-cw.qmd
      - text: ğŸ’» Homework
        href: listing-danl-410-hw.qmd
      - text: ğŸ“ Exams
        href: listing-danl-410-ex.qmd
        
      - section: ğŸ—£ï¸ï¸ Project
        contents:
          - text: ğŸ§¾ğŸ“Œ Research Kick-off Report
            href: danl-rw/danl-410-project-kickoff.qmd
            
      - section: ğŸ—“ï¸ Weeks
        contents:
          - text: Week 01
            href: danl-wk/wk-01.qmd
          - text: Week 02
            href: danl-wk/wk-02.qmd
      
        
  page-footer: 
    border: false
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2026"
    # foreground: dark
    # background: '#9b4e55' 


execute:
  echo: true
  eval: true
  message: false
  warning: false
  
format:
  html: 
    grid:
      margin-width: 400px
      sidebar-width: 200px
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css"/>
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    include-after-body: [sidebar-button-mobile.html]
